# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-03 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='is_favourite',
            field=models.BooleanField(default=False),
        ),
    ]
