# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-01 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0002_songs_is_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='is_favourite',
        ),
    ]
