# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-04-01 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0003_remove_songs_is_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='album_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
